branches: master
repositoryUrl: https://github.com/gwatcha/reaper-keys
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/github"
  - assets:
    - dist/reaper-keys
- "@semantic-release/git"
