branches: master
repositoryUrl: https://github.com/gwatcha/reaper-keys
plugins: |
  @semantic-release/github
  @semantic-release/changelog@3.0.0
  @semantic-release/commit-analyzer
  @semantic-release/release-notes-generator
