return {
	timeline_motion = {
		["<M-+>"] = "DecreaseGrid",
		["<M-->"] = "IncreaseGrid",
		["<C-$>"] = "ProjectEnd",
		["f"] = "PlayPosition",
		["x"] = "MousePosition",
		["["] = "LoopStart",
		["]"] = "LoopEnd",
		["<M-left>"] = "PrevTimeSignatureMarker",
		["<M-right>"] = "NextTimeSignatureMarker",
		["<M-h>"] = "Left10Pix",
		["<M-l>"] = "Right10Pix",
		["<M-H>"] = "Left40Pix",
		["<M-L>"] = "Right40Pix",
		["h"] = "LeftGridDivision",
		["<left>"] = "LeftGridDivision",
		["l"] = "RightGridDivision",
		["<right>"] = "RightGridDivision",
		["H"] = "PrevMeasure",
		["L"] = "NextMeasure",
		["<S-right>"] = "NextMeasure",
		["<S-left>"] = "PrevMeasure",
		["<C-i>"] = "MoveRedo",
		["<C-o>"] = "MoveUndo",
		["<C-h>"] = "Prev4Beats",
		["<C-l>"] = "Next4Beats",
		["<C-H>"] = "Prev4Measures",
		["<C-L>"] = "Next4Measures",
		["`"] = "MarkedTimelinePosition",
	},
	timeline_operator = {
		["r"] = "Record",
		["<C-p>"] = "DuplicateTimeline",
		["t"] = "PlayAndLoop",
		["|"] = "CreateMeasures",
		["<C-|>"] = "CreateProjectTempo",
	},
	timeline_selector = {
		["~"] = "MarkedRegion",
		["!"] = "LoopSelection",
		["<CS-right>"] = "TimeSelectionShiftedRight",
		["<CS-left>"] = "TimeSelectionShiftedLeft",
		["i"] = {
			"+inner",
			{
				["<M-w>"] = "AutomationItem",
				["l"] = "AllTrackItems",
				["r"] = "Region",
				["p"] = "ProjectTimeline",
				["w"] = "Item",
				["W"] = "BigItem",
				["<M-l>"] = "AllTrackEnvelopePoints"
			},
		},
	},
	visual_timeline_command = {
		["v"] = "SetModeNormal",
		["o"] = "SwitchTimelineSelectionSide",
	},
	command = {
		["<V-1>"] = "VrtlBtn1",
		["<V-2>"] = "VrtlBtn2",
		["<V-3>"] = "VrtlBtn3",
		["<V-4>"] = "VrtlBtn4",
		["<V-5>"] = "VrtlBtn5",
		["<V-6>"] = "VrtlBtn6",
		["<V-7>"] = "VrtlBtn7",
		["<V-8>"] = "VrtlBtn8",
		["<V-9>"] = "VrtlBtn9",
		["<V-10>"] = "VrtlBtn10",
		["<V-11>"] = "VrtlBtn11",
		["<V-12>"] = "VrtlBtn12",
		["<V-13>"] = "VrtlBtn13",
		["<V-14>"] = "VrtlBtn14",
		["<V-15>"] = "VrtlBtn15",
		["<V-16>"] = "VrtlBtn16",
		["<C-s>"] = "SaveProject",
		["."] = "RepeatLastCommand",
		["@"] = "PlayMacro",
		[","] = "RecordMacro",
		["m"] = "Mark",
		["~"] = "MarkedRegion",
		["<C-'>"] = "DeleteMark",
		["<S-right>"] = "NextRegion",
		["<S-left>"] = "PrevRegion",
		["<C-r>"] = "Redo",
		["u"] = "Undo",
		["R"] = "ToggleRecord",
		["T"] = "Play",
		["<C-T>"] = "PlayAndSkipTimeSelection",
		["<M-t>"] = "PlayFromMousePosition",
		["<M-T>"] = "PlayFromMouseAndSoloTrack",
		["<C-t>"] = "PlayFromEditCursorAndSoloTrackUnderMouse",
		["tt"] = "PlayFromTimeSelectionStart",
		["F"] = "Pause",
		["<C-z>"] = "ZoomUndo",
		["<C-Z>"] = "ZoomRedo",
		["v"] = "SetModeVisualTimeline",
		["<M-v>"] = "ClearTimelineSelectionAndSetModeVisualTimeline",
		["<C-SPC>"] = "ToggleViewMixer",
		["<return>"] = "StartStop",
		["X"] = "MoveToMousePositionAndPlay",
		["dr"] = "RemoveRegion",
		["!"] = "ToggleLoop",
		["<C-a>"] = "ToggleBetweenReadAndTouchAutomationMode",
		["<M-n>"] = "ShowNextFx",
		["<M-N>"] = "ShowPrevFx",
		["<M-g>"] = "FocusMain",
		["<M-f>"] = "ToggleShowFx",
		["<M-F>"] = "CloseFx",
		["<CM-f>"] = "MidiLearnLastTouchedFxParam",
		["<CM-m>"] = "ModulateLastTouchedFxParam",
		["<M-x>"] = "ShowBindingList",
		["<C-m>"] = "TapTempo",
		['"'] = {
			"+snapshots",
			{
				["j"] = "RecallNextSnapshot",
				["k"] = "RecallPreviousSnapshot",
				["D"] = "DeleteAllSnapshots",
				["t"] = "ToggleSnapshotsWindow",
				["y"] = "CopyCurrentSnapshot",
				["p"] = "PasteSnapshot",
				["r"] = "RecallCurrentSnapshot",
				["#"] = {
					"+recall #",
					{
						["1"] = "RecallSnapshot1",
						["2"] = "RecallSnapshot2",
						["3"] = "RecallSnapshot3",
						["4"] = "RecallSnapshot4",
						["5"] = "RecallSnapshot5",
						["6"] = "RecallSnapshot6",
						["7"] = "RecallSnapshot7",
						["8"] = "RecallSnapshot8",
						["9"] = "RecallSnapshot9",
					},
				},
			},
		},
	},
}
