return {
	timeline_selector = {
		["s"] = "SelectedNotes",
	},
	timeline_operator = {
		["d"] = "CutNotes",
		["y"] = "CopyNotes",
		["c"] = "FitNotes",
		["a"] = "InsertNote",
		["g"] = "JoinNotes",
		["s"] = "SelectNotes",
		["z"] = "MidiZoomTimeSelection",
	},
	timeline_motion = {
		["<right>"] = "RightMidiGridDivision",
		["<left>"] = "LeftMidiGridDivision",
		["l"] = "MoveNoteAndCursorRight",
		["h"] = "MoveNoteAndCursorLeft",
		["("] = "MidiTimeSelectionStart",
		[")"] = "MidiTimeSelectionEnd",
		["w"] = "NextNoteStart",
		["b"] = "PrevNoteStart",
		["W"] = "NextBigNoteStart",
		["B"] = "PrevBigNoteStart",
		["E"] = "NextBigNoteEnd",
		["e"] = "NextNoteEnd",
		["<up>"] = "MoveNoteUpSemitone",
		["<down>"] = "MoveNoteDownSemitone",
		["<S-up>"] = "MoveNoteUpOctave",
		["<S-down>"] = "MoveNoteDownOctave",
		["<S-right>"] = "LengthenNotes",
		["<S-left>"] = "ShortenNotes",
		["n"] = "AddNextNoteToSelection",
		["N"] = "AddPrevNoteToSelection",
		["<TAB>"] = "JumpToNextNote",
		["<S-TAB>"] = "JumpToPrevNote",
		["<C-w>"] = "ActivateNextMidiTrack",
		["<C-W>"] = "ActivatePrevMidiTrack",
	},
	command = {
		["<ESC>"] = "ResetMidi",
		[":"] = "jumpToBar",
		["n"] = "AddNextNoteToSelection",
		["N"] = "AddPrevNoteToSelection",
		["+"] = "MidiZoomInVert",
		["-"] = "MidiZoomOutVert",
		["<C-+>"] = "MidiZoomInHoriz",
		["<C-->"] = "MidiZoomOutHoriz",
		["Z"] = "CloseWindow",
		["p"] = "MidiPaste",
		["S"] = "UnselectAllEvents",
		["Y"] = "CopySelectedEvents",
		["D"] = "CutSelectedEvents",
		["k"] = "PitchUp",
		["j"] = "PitchDown",
		["K"] = "PitchUpOctave",
		["zp"] = "MidiZoomContent",
		["J"] = "PitchDownOctave",
		["<SPC>"] = {
			"+leader commands",
			{
				["q"] = "CloseUndockedMidiEditorOrPassToMainWindow",
				["<SPC>"] = "ShowMidiActionList",
				["m"] = {
					"+midi",
					{
						["g"] = "SetMidiGridDivision",
						["q"] = "Quantize",
					},
				},
				["A"] = { "+Arrange", {
					["t"] = "AddTextOrnament",
					["e"] = "ExplodeRoutineFromAnnotations"
				} },
				["c"] = { "+CCs", {
					["t"] = "ToggleUsedCC",
				} },
				["k"] = { "+key", {
					["s"] = "toggleKeySnap",
					["f"] = "forceSelectedNotesToKey"
				} },
				["C"] = { "+Chord", {
					["i"] = "insertChordSymbol",
					["s"] = { "+select", {
						["b"] = "SelectBottomNotes",
						["t"] = "SelectTopNotes",
						["m"] = "SelectMiddleNotes",
						["et"] = "SelectAllButTop",
						["eb"] = "SelectAllButBottom",
						["em"] = "SelectAllButMiddle",
					} },
					["d"] = { "+drop", {
						["2"] = "drop2",
						["3"] = "drop3",
						["4"] = "drop24",
					} },
					["D"] = { "+doublings", {
						["u"] = { "+up", {
							["8"] = "doubleOctUp",
							["7"] = "doubleSeventhUp",
							["6"] = "doubleSixthUp",
							["5"] = "doubleFifthUp",
							["4"] = "doubleFourthUp",
							["3"] = "doubleThirdUp",
						} },
						["d"] = { "+down", {
							["8"] = "doubleOctDown",
							["7"] = "doubleSeventhDown",
							["6"] = "doubleSixthDown",
							["5"] = "doubleFifthDown",
							["4"] = "doubleFourthDown",
							["3"] = "doubleThirdDown",
						} },
						["t"] = "doubleTopOctUp",
						["b"] = "doubleBottomOctDown",
					} },
					["S"] = "soliHarmonize",
				} },
				["v"] = {
					"+view",
					{
						["d"] = "DrumsView",
						["e"] = "EventView",
						["n"] = "NotationView",
						["p"] = "PianoRollView",
					},
				},
			},
		},
		["<M-g>"] = "InsertG",
		["<M-s>"] = "InsertGb",
		["<M-f>"] = "InsertF",
		["<M-e>"] = "InsertE",
		["<M-m>"] = "InsertEb",
		["<M-d>"] = "InsertD",
		["<M-r>"] = "InsertDb",
		["<M-c>"] = "InsertC",
		["<M-b>"] = "InsertB",
		["<M-h>"] = "InsertBb",
		["<M-a>"] = "InsertA",
		["<M-l>"] = "InsertAb",
		["<M-G>"] = "InsertChordG",
		["<M-S>"] = "InsertChordGb",
		["<M-F>"] = "InsertChordF",
		["<M-E>"] = "InsertChordE",
		["<M-M>"] = "InsertChordEb",
		["<M-D>"] = "InsertChordD",
		["<M-R>"] = "InsertChordDb",
		["<M-C>"] = "InsertChordC",
		["<M-B>"] = "InsertChordB",
		["<M-H>"] = "InsertChordBb",
		["<M-A>"] = "InsertChordA",
		["<M-L>"] = "InsertChordAb",
	},
}
