return {
  timeline_selector = {
    ["s"] = "SelectedNotes",
  },
  timeline_operator = {
    ["d"] = "CutNotes",
    ["y"] = "CopyNotes",
    ["c"] = "FitNotes",
    ["a"] = "InsertNote",
    ["g"] = "JoinNotes",
    ["s"] = "SelectNotes",
    ["z"] = "MidiZoomTimeSelection",
  },
  timeline_motion = {
    ["l"] = "RightMidiGridDivision",
    ["h"] = "LeftMidiGridDivision",
    ["<right>"] = "MoveNoteAndCursorRight",
    ["<left>"] = "MoveNoteAndCursorLeft",
    ["("] = "MidiTimeSelectionStart",
    [")"] = "MidiTimeSelectionEnd",
    ["w"] = "NextNoteStart",
    ["b"] = "PrevNoteStart",
    ["W"] = "NextNoteSamePitchStart",
    ["B"] = "PrevNoteSamePitchStart",
    ["e"] = "EventSelectionEnd",
    ["<up>"] = "MoveNoteUpSemitone",
    ["<down>"] = "MoveNoteDownSemitone",
    ["<S-up>"] = "MoveNoteUpOctave",
    ["<S-down>"] = "MoveNoteDownOctave",
    ["<S-right>"] = "LengthenNotes",
    ["<S-left>"] = "ShortenNotes",
    ["n"] = "AddNextNoteToSelection",
    ["N"] = "AddPrevNoteToSelection",
  },
  command = {
    ["+"] = "MidiZoomInVert",
    ["-"] = "MidiZoomOutVert",
    ["<C-+>"] = "MidiZoomInHoriz",
    ["<C-->"] = "MidiZoomOutHoriz",
    ["Z"] = "CloseWindow",
    ["p"] = "MidiPaste",
    ["S"] = "UnselectAllEvents",
    ["Y"] = "CopySelectedEvents",
    ["x"] = "CutSelectedEvents",
    ["k"] = "PitchUp",
    ["j"] = "PitchDown",
    ["K"] = "PitchUpOctave",
    ["zp"] = "MidiZoomContent",
    ["J"] = "PitchDownOctave",
    ["V"] = "SelectAllNotesAtPitch",
    ["<M-k>"] = "MoveNoteUpSemitone",
    ["<M-j>"] = "MoveNoteDownSemitone",
    ["<M-K>"] = "MoveNoteUpOctave",
    ["<M-J>"] = "MoveNoteDownOctave",
    ["<SPC>"] = { "+leader commands", {
      ["<SPC>"] = "ShowMidiActionList",
      ["m"] = { "+midi", {
                  ["g"] = "SetMidiGridDivision",
                  ["q"] = "Quantize",
      }},
      ["c"] = { "+CCs", {
                  ["t"] = "ToggleUsedCC"
      }}
    }},
    ["<M-g>"] = "InsertG",
    ["<M-s>"] = "InsertGb",
    ["<M-f>"] = "InsertF",
    ["<M-e>"] = "InsertE",
    ["<M-m>"] = "InsertEb",
    ["<M-d>"] = "InsertD",
    ["<M-r>"] = "InsertDb",
    ["<M-c>"] = "InsertC",
    ["<M-b>"] = "InsertB",
    ["<M-h>"] = "InsertBb",
    ["<M-a>"] = "InsertA",
    ["<M-l>"] = "InsertAb",
    ["<TAB>"] = "JumpToNextNote",
    ["<S-TAB>"] = "JumpToPrevNote",
  },
}
